### PR TITLE
Make created cache dir mask as option and default to 0777

### LINKED ISSUE #24: Generated type class directory permissions
Please consider using the default permissions (`0777`) when creating directories for generated type classes. Using `0775` causes permission errors when the classes need to be deleted and recreated under a different user (e.g. by `CompileCacheWarmer` from `GraphQLBundle`).

`Failed to remove file "<snip>/dev/overblog/graphql-bundle/__definitions__/FooBarType.php": unlink(<snip>/overblog/graphql-bundle/__definitions__/FooBar.php): Permission denied.`

https://github.com/overblog/GraphQLPhpGenerator/blob/f6881be5b469213b4d55be947ce2ce6fe946107b/src/Generator/AbstractTypeGenerator.php#L364

This can happen often during Symfony app development where the cache is populated automatically both via `bin/console` (runs under `root` in docker) and the webserver (runs under `www-data`) when some files are changed.

Looking at the cache directory, `overblog/graphql-bundle/__definitions__` is the only path that has `0755` permissions. Everything else (doctrine, pools, containers, twig, etc.) has `0777`.

### PR DESCRIPTION
**Pull request by Vincz**
Make the created cache dir default to mask 0777 instead of 0775 to avoid permission errors on cache removal. Fix #24

### CODE REVIEW

File: src/Generator/AbstractTypeGenerator.php [hunk 1]
```diff
@@ -62,13 +62,19 @@ function (%s) <closureUseStatements>{
      */
     private $expressionLanguage;
 
+    /**
+     * @var int
+     */
+    protected $cacheDirMask;
```
Comment (mcg-web) [inline src/Generator/AbstractTypeGenerator.php]: Since the value can be set using construct making this private in a first place could ease maintenance.
```suggestion
    private $cacheDirMask;
```

File: src/Generator/AbstractTypeGenerator.php [hunk 2]
```diff
@@ -62,13 +62,19 @@ function (%s) <closureUseStatements>{
...
+
     /**
      * @param string           $classNamespace The namespace to use for the classes.
      * @param string[]|string  $skeletonDirs
      */
-    public function __construct($classNamespace = self::DEFAULT_CLASS_NAMESPACE, $skeletonDirs = [])
+    public function __construct($classNamespace = self::DEFAULT_CLASS_NAMESPACE, $skeletonDirs = [], $cacheDirMask = 0777)
```
Comment (mcg-web) [inline src/Generator/AbstractTypeGenerator.php]: This change could introduce some secure issue so we should just give a way to override the value without changing it for this bugfix version, we'll change it in next major version.
```suggestion
    public function __construct($classNamespace = self::DEFAULT_CLASS_NAMESPACE, $skeletonDirs = [], $cacheDirMask = 0775)
```

**Comment by mcg-web** [comment]
In GraphQL Bundle [modifying this line](https://github.com/overblog/GraphQLBundle/blob/master/src/Generator/TypeGenerator.php#L49) does the work. Changing dir mask can be consider as BC since this change how files is generated so this will be release in 0.8, [the bundle requires 0.7 of this lib](https://github.com/overblog/GraphQLBundle/blob/0.11/composer.json#L34) so we must modify the bundle anyway. I prefer setting the value of cache dir mask variable only by construct since this is a configuration argument (so no need to change it on compile time). I'm no fan of the global static variable since you loose flexibility between different instances.

**Comment by mcg-web** [comment]
Done @Vincz! The bundle fix should be submit for 0.11 version. Thanks again for your contribution!
